### ISSUE TITLE
Validation in moleculer-web skips all middleware

### ISSUE THREAD

**Issue by mailaneel** [ice-services/moleculer-web#31]
https://github.com/ice-services/moleculer-web/blob/880c0c3df081e29d4f64b746433589ba54d39bbd/src/index.js#L645

Validator adds a validation middleware which does the params validation. by doing this in `moleculer-web` it skips all other middleware
  
`validator.validate` throws ValidationError

**Comment by icebob** [comment]
Fixed and released. 
https://github.com/ice-services/moleculer-web/releases/tag/v0.6.2
