### ISSUE TITLE
404 should be returned instead of 501 for ServiceNotFoundError

### ISSUE THREAD

**Issue by HCanber** [ice-services/moleculer-web#7]
moleculer-web: 0.3.3

Issuing a __GET__ to a non existing route, for example http://localhost:3000/does-not-exist returns

```json
{
  "name": "ServiceNotFoundError",
  "message": "Service 'does-not-exist' is not available!",
  "code": 501,
  "type": null,
  "data": {
    "action": "does-not-exist"
  }
}
```

and sets the HTTP header
```http
Status Code:501 Not Implemented
```

This status code is used when using a _request method_ (standard ones are GET, POST, HEAD, PUT, ...) that the web server does not support.
I'm using the __GET__ request method, which the web server supports, so I would not expect to get a _501_ in this case.

For non existing resources, _404 Not Found_ should be used. It is a client error and should therefore be in the _4xx_ range (_5xx_ are used for server errors).

I know the _501_ originates from an error in _moleculer_ and just passes through, but it's confusing to get it as the HTTP status code.

501: https://tools.ietf.org/html/rfc7231#section-6.6.2
404: https://tools.ietf.org/html/rfc7231#section-6.5.4
Request methods: https://tools.ietf.org/html/rfc7231#section-4

**Comment by icebob** [comment]
Thank your suggestion. In this case I will change the code of `ServiceNotFoundError` in Moleculer.

**Comment by icebob** [comment]
Fixed in https://github.com/ice-services/moleculer/commit/cd75e434dabc3a4352d6e746692a1adb6752331e
In the next version will be released.
