### ISSUE TITLE
Before setting Content-Type header, check to see if it's not already set

### ISSUE THREAD

**Issue by demetriusnunes** [ice-services/moleculer-web#8]
I wrote an afterHook to set the content type to include the utf-8 charset option (I have international characters in my json responses) like this:
```
onAfterCall(ctx, route, req, res) {
  res.setHeader('Content-Type', 'application/json; charset=utf-8');
}
```

Unfortunately, this gets overwritten by the built-in behavior.

I think it should check whether or not the header is already set before setting it.

**Comment by demetriusnunes** [comment]
By reading the code, I found out that I can set a `resposeType` property in my service action to override that behavior, but I think that's not a good design choice, as my service should not be aware of the HTTP protocol details being used.

**Comment by icebob** [comment]
Ok, I will make a check when set responseType. And if it is exists, don't change it.

**Comment by icebob** [comment]
Better solution is to overwrite the `sendResponse(ctx, route, req, res, data, responseType)`  method

```js
module.exports = {
    mixins: [ApiGwService],

    methods: {
        sendResponse(ctx, route, req, res, data, responseType) {
            res.end(JSON.stringify(data));
        }
    }
}
```
