### ISSUE TITLE
How to add new action/service without restart

### ISSUE THREAD

**Issue by malasgowda** [ice-services/moleculer-web#9]
How to add a new service/action to a moleculer-web  service without restarting . 
Example i have created a index.js ad loaded math.service .js which contains only add functionality and started the service .Its working fine  now i added code for sub in math.service.js file and reloading it but i am unable to access this action without restarting index .js

Please let me know how can i add a new service/ action without restarting

**Comment by icebob** [comment]
Currently you can't reload services files without restarting.

> I plan that I add a hot-reload service feature in the future.
